# PVC 먼저 선언
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 837126493345.dkr.ecr.ap-northeast-2.amazonaws.com/goormthon-2/backend:build-19
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: clova-stt-secret
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: audio-storage        # 추가
          mountPath: /app/audio      # Spring에서 이 경로로 저장
      volumes:
      - name: config-volume
        configMap:
          name: backend-config
      - name: audio-storage          # 추가
        persistentVolumeClaim:
          claimName: audio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080